#!/bin/bash --norc

THIS_DIR=$(dirname "$0")

exec "${THIS_DIR}"/ld-linux-x86-64.so.2 \
  --inhibit-cache \
  "{native_sysroot}/usr/bin/{target_prefix}/$(basename $0)" \
  -B "${THIS_DIR}" \
  -wrapper "${THIS_DIR}"/ld-linux-x86-64.so.2 \
  "$@"