workspace(
    name = "bazel-toolchains-yocto-test",
)

local_repository(
    name = "bazel_toolchains_yocto",
    path = "../..",
)

load("@bazel_toolchains_yocto//yocto:repositories.bzl", "bazel_toolchains_yocto_dependencies")

bazel_toolchains_yocto_dependencies()

load("@bazel_toolchains_yocto//yocto:defs.bzl", "http_yocto_toolchain_archive", "http_yocto_toolchain_file", "local_yocto_toolchain")

http_yocto_toolchain_file(
    name = "core2-64-poky-linux",
    environment_setup = "environment-setup-core2-64-poky-linux",
    executable = True,
    sha256 = "110d70bf8042d8262790462e48245d37190884d3b6f813d9913eae31d0abcb71",
    urls = ["https://downloads.yoctoproject.org/releases/yocto/yocto-5.0.10/toolchain/x86_64/poky-glibc-x86_64-core-image-sato-core2-64-qemux86-64-toolchain-5.0.10.sh"],
)

http_yocto_toolchain_file(
    name = "cortexa57-poky-linux_new",
    build_file = "@//third_party/cortexa57-poky-linux:BUILD.cortexa57-poky-linux",
    environment_setup = "environment-setup-cortexa57-poky-linux",
    sha256 = "de5340bf0bc5a535988d63e0ad88792658982500ef265403394705b844b9c10f",
    urls = ["https://downloads.yoctoproject.org/releases/yocto/yocto-5.0.10/toolchain/x86_64/poky-glibc-x86_64-core-image-sato-cortexa57-qemuarm64-toolchain-5.0.10.sh"],
)

http_yocto_toolchain_archive(
    name = "core2-64-poky-linux-4_0",
    environment_setup = "environment-setup-core2-64-poky-linux",
    sdk_installer = "poky-glibc-x86_64-core-image-sato-core2-64-qemux86-64-toolchain-4.0.4.sh",
    sha256 = "1db6f09c8f9c6c1c1c6925b1dddeeed46d91c668fa4c911c79c3741b54040fc4",
    urls = ["http://localhost:8080/downloads/poky-glibc-x86_64-core-image-sato-core2-64-qemux86-64-toolchain-4.0.4.tar.gz"],
)

local_yocto_toolchain(
    name = "yocto-local",
)
